repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.7 # Ruff version
    hooks:
      - id: ruff # Run the linter.
        name: Run Linter Check (Ruff)
        args: [ --fix ]
        files: ^(src|tests|examples)/
      - id: ruff-format       # Run the formatter.
        name: Run Formatter (Ruff)